### ISSUE TITLE
关于论文中提到的372条polyimides数据

### ISSUE THREAD

**Issue by Rainsmumu** [hkqiu/PPP-1_PredictionTg4Polyimides#1]
作者你好

最近看了你的论文，你在文中提到了论文中所有使用的数据都放在了这个仓库，但我似乎没有找到372条polyimides的数据集，请问我要如何获取这个数据集呢？

感谢你的帮助

**Comment by hkqiu** [comment]
您好，感谢您对本工作的兴趣。我没有找到您的邮箱，您可email to zysun@ciac.ac.cn获取数据。
